apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-local-1
  labels:
    type: local
    tier: data
  namespace: project-name
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/mysql-pv-local-1
---

