---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project-name
  labels:
    app: mysql
    tier: data
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
    tier: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: project-name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: project-name
  labels:
    app: mysql
    tier: data
spec:
  selector:
    matchLabels:
      app: mysql
      tier: data
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: data
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---

