---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: flask-uwsgi-nginx
  namespace: project-name
spec:
  selector:
    matchLabels:
      app: flaskapp
      tier: rest-engine
  replicas: 3
  template:
    metadata:
      labels:
        app: flaskapp
        tier: rest-engine
    spec:
      containers:
      - name: flask-uwsgi-nginx
        image: nareshganesan/flask-uwsgi-nginx:v2.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "guestbook"
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # instead access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: project-name
  labels:
    app: flaskapp
    tier: rest-engine
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: flaskapp
    tier: rest-engine
---
