apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv-local-1
  labels:
    type: local
    tier: data
  namespace: vcs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/gogs-pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv-local-2
  labels:
    type: local
    tier: data
  namespace: vcs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/gogs-pv-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv-local-3
  labels:
    type: local
    tier: data
  namespace: vcs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/gogs-pv-3
---
